### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by PipeYume** [nornagon/cdda-json-lsp#1]
[Info  - 03:17:56] listing modinfos
[Error - 03:17:56] Error reading mod info at file:///d%3A/cdda-windows-tiles-x64-2024-01-09-0623/data/mods/JojoStands/modinfo.json: process is not defined
![image](https://github.com/nornagon/cdda-json-lsp/assets/81861009/27abfefe-2b67-4d05-b6ad-681f3a2f5c40)

The error is because of `path.relative`
This problem relates to `path-browserify`, like this issue https://github.com/browserify/path-browserify/issues/29

I temporarily solve it by not considering the relative path, but only concider the whole workspace:
<img width="607" alt="image" src="https://github.com/nornagon/cdda-json-lsp/assets/81861009/9c569e9b-bc5b-472e-996e-4b7dec27cf71">

**Comment by nornagon** [comment]
I wasn't able to repro this but that path-browserify issue did lead me to the code that invokes `process` under the hood, and I think I was able to remedy it. Give the latest published version of the extension another shot.
